// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('navegacion', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('navegacion', async function() {
    // Test name: navegacion
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://cursosdedesarrollo.com/")
    // 2 | setWindowSize | 1920x1080 | 
    await driver.manage().window().setRect({ width: 1920, height: 1080 })
    // 3 | type | id=wp-block-search__input-1 | nas
    await driver.findElement(By.id("wp-block-search__input-1")).sendKeys("nas")
    // 4 | click | css=.wp-block-search__button | 
    await driver.findElement(By.css(".wp-block-search__button")).click()
    // 5 | assertText | css=header.page-header h1 | Search results for: nas
    assert(await driver.findElement(By.css("header.page-header h1")).getText() == "Search results for: nas")
  })
})
