// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('software', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('software', async function() {
    // Test name: software
    // Step # | name | target | value
    // 1 | open | /wiki/Wikipedia:Portada | 
    await driver.get("https://es.wikipedia.org/wiki/Wikipedia:Portada")
    // 2 | assertElementPresent | id=Bienvenidos_a_Wikipedia, | 
    {
      const elements = await driver.findElements(By.id("Bienvenidos_a_Wikipedia,"))
      assert(elements.length)
    }
    // 3 | type | id=searchInput | software
    await driver.findElement(By.id("searchInput")).sendKeys("software")
    // 4 | click | id=searchButton | 
    await driver.findElement(By.id("searchButton")).click()
    // 5 | assertText | id=firstHeading | Software
    assert(await driver.findElement(By.id("firstHeading")).getText() == "Software")
  })
})
